---
title: "Pretty Decay Curves"
output: html_notebook
---


```{r}
library('Rmisc')
library('tidyverse')
library('ggplot')

```


Should be able to 

```{r}
source('GraphingTools.r')
df <- read_in_and_preprocessor("~/Desktop/siLucVssiSki.csv")


xc <- summarySE(df, measurevar="Abundance", groupvars = c("Time", "Substrate", "Treatment"), na.rm=T)
xc

ggplot(df, aes(x=Time, y=log(Abundance), color=Treatment)) + 
  geom_point() + 
  facet_wrap(~Substrate+Replicate) +
  geom_smooth(method="lm", formula=(y~x), se=F)

```
```{r}
source("GraphingTools.r")
test <- filter(df, Substrate=="BG-NSD", Treatment=="siLuc", Replicate==1)

x <- find_half_life(test)
x


```


```{r}
ski_df <- read.csv("./NSD_siLuc_siSki/NSD_LucVsSki_new.csv")
ski_df$Replicate <- as.factor(ski_df$Replicate)

ski_df <- filter(ski_df, Substrate=="BG-NSD")

ski.summary <- summarySE(ski_df, measurevar="Abundance", groupvars = c("Time", "Substrate", "Treatment"), na.rm=T)

ski.summary
for (c in 1:3){
  ski.model <- lm( formula(log(Abundance)~Time),filter(ski_df,Treatment=="siSki" & Replicate==c))
  print(coef(ski.model)[2])
}
```


```{r}
ggplot(ski.summary, aes(x=Time, y=log(Abundance), color=Treatment)) + geom_point(size=3) + geom_smooth(method="lm", formula=(y~x), size=1.3, se=F) + geom_errorbar(aes(ymin=log(Abundance-se), ymax=log(Abundance+se), width=5)) +theme_minimal() + theme(panel.grid.major.y=element_blank(), panel.grid.minor.x=element_blank(), panel.grid.major.x=element_blank(), panel.border=element_rect(size=1, fill=NA, color='lightgrey'), panel.grid.minor.y=element_line(size=1, color='lightgrey')) + scale_y_continuous(lim=c(-1.21,0.1),minor_breaks = c(0.000001,-0.105360516, -0.223143551, -0.356674944, -0.510825624, -0.693147181, -0.916290732, -1.203972804, -1.609437912, -2.302585093)) + scale_color_manual(values=c( "#000000","#A4A4A5")) + scale_x_continuous(breaks=c(0,120,240,360))

ggsave("NSD_siSki.tiff")

```


```{r}
df <- read.csv("./NSD_siLuc_siA1/NSD_LucVsA1.csv")
df$Replicate <- as.factor(df$Replicate)

df <- filter(df, Substrate=="BG-NSD")

df.summary <- summarySE(df, measurevar="Abundance", groupvars = c("Time", "Substrate", "Treatment"), na.rm=T)

df.summary

for (c in 1:3){
  df.model <- lm( formula(log(Abundance)~Time),filter(df,Treatment=="siA1" & Replicate==c))
  print(coef(df.model)[2])
}

ggplot(df.summary, aes(x=Time, y=log(Abundance), color=Treatment)) + geom_point(size=3) + geom_smooth(method="lm", formula=(y~x), se=F, size=1.3) + geom_errorbar(aes(ymin=log(Abundance-se), ymax=log(Abundance+se), width=5)) +theme_minimal() + theme(panel.grid.major.y=element_blank(), panel.grid.minor.x=element_blank(), panel.grid.major.x=element_blank(), panel.border=element_rect(size=1, fill=NA, color='lightgrey'), panel.grid.minor.y=element_line(size=1, color='lightgrey')) + scale_y_continuous(lim=c(-1.21,0.1),minor_breaks = c(0.000001,-0.105360516, -0.223143551, -0.356674944, -0.510825624, -0.693147181, -0.916290732, -1.203972804, -1.609437912, -2.302585093)) + scale_color_manual(values=c( "#A4A4A5","#000000")) + scale_x_continuous(breaks=c(0,120,240,360))

ggsave("NSD_siA1.tiff")
```

```{r}
df <- read.csv("./NSD_siLuc_siA1/NSD_LucVsA1.csv")
df$Replicate <- as.factor(df$Replicate)

df <- filter(df, Substrate=="BG-PTC")

df.summary <- summarySE(df, measurevar="Abundance", groupvars = c("Time", "Substrate", "Treatment"), na.rm=T)

df.summary

for (c in 1:3){
  df.model <- lm( formula(log(Abundance)~Time),filter(df,Treatment=="siLuc" & Replicate==c))
  print(coef(df.model)[2])
}

log(0.4148588, 10)
ggplot(df.summary, aes(x=Time, y=log(Abundance), color=Treatment)) + geom_point(size=3) + geom_smooth(method="lm", formula=(y~x), se=F, size=1.3) + geom_errorbar(aes(ymin=log(Abundance-se), ymax=log(Abundance+se), width=5)) +theme_minimal() + theme(panel.grid.major.y=element_blank(), panel.grid.minor.x=element_blank(), panel.grid.major.x=element_blank(), panel.border=element_rect(size=1, fill=NA, color='lightgrey'), panel.grid.minor.y=element_line(size=1, color='lightgrey')) + scale_y_continuous(lim=c(-1.8,0.1),minor_breaks = c(0.000001,-0.105360516, -0.223143551, -0.356674944, -0.510825624, -0.693147181, -0.916290732, -1.203972804, -1.609437912, -2.302585093)) + scale_color_manual(values=c( "#A4A4A5","#000000")) + scale_x_continuous(breaks=c(0,120,240,360))

ggsave("PTC_siA1.tiff")
```

```{r}
df <- read.csv("./tpi.csv")


df <- filter(df, Substrate=="TPI-NS")

df.model <- lm( formula(log(Abundance)~Time),filter(df,Treatment=="siA1"))
print(coef(df.model)[2])




log(0.4148588, 10)
ggplot(df, aes(x=Time, y=log(Abundance), color=Treatment)) + geom_point(size=3) + geom_smooth(method="lm", formula=(y~x), se=F, size=1.3) +theme_minimal() + theme(panel.grid.major.y=element_blank(), panel.grid.minor.x=element_blank(), panel.grid.major.x=element_blank(), panel.border=element_rect(size=1, fill=NA, color='lightgrey'), panel.grid.minor.y=element_line(size=1, color='lightgrey')) + scale_y_continuous(lim=c(-1.21,0.1),minor_breaks = c(0.000001,-0.105360516, -0.223143551, -0.356674944, -0.510825624, -0.693147181, -0.916290732, -1.203972804, -1.609437912, -2.302585093)) + scale_color_manual(values=c( "#A4A4A5","#000000")) + scale_x_continuous(breaks=c(0,120,240,360))

ggsave("TPI-NS_siA1.tiff")
```

```{r}
df <- read.csv("./NSD_A1_Addbacks/Addbacks.csv")

df = filter(df, (Replicate==1 | Replicate==2) & Treatment != "EA" )

df


df.summary <- summarySE(df, measurevar="Abundance", groupvars = c("Time", "Substrate", "Treatment"), na.rm=T)

ggplot(df.summary, aes(x=Time, y=log(Abundance), color=Treatment, linetype=Treatment)) + geom_point(size=3) + geom_smooth(method="lm", formula=(y~x), se=F, size=1.3) + geom_errorbar(aes(ymin=log(Abundance-se), ymax=log(Abundance+se), width=5)) +theme_minimal() + theme(panel.grid.major.y=element_blank(), panel.grid.minor.x=element_blank(), panel.grid.major.x=element_blank(), panel.border=element_rect(size=1, fill=NA, color='lightgrey'), panel.grid.minor.y=element_line(size=1, color='lightgrey')) + scale_y_continuous(lim=c(-1.21,0.1),minor_breaks = c(0.000001,-0.105360516, -0.223143551, -0.356674944, -0.510825624, -0.693147181, -0.916290732, -1.203972804, -1.609437912, -2.302585093)) + scale_x_continuous(breaks=c(0,120,240,360)) + scale_color_manual(values=c( "#A4A4A5","#000000", "#A4A4A5")) + scale_linetype_manual(values=c(1,1,4))

ggsave('Addbacks.tiff')
```

